on:
  push:
    branches:    
      - main
jobs:
  my_first_job:
    runs-on: ubuntu-latest,
    name: My first job,
    steps:
    - name: Checkout
        uses: actions/checkout@master
    
    - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BRANCH: main
            FOLDER: build
            BUILD_SCRIPT: npm install && npm run test
