on:
  push:
    branches:    
      - main
jobs:
  my-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      run: npm install
    - name: Build
      run: |
        npm install parcel
        npm run-script test       
  my-deploy:
    runs-on: ubuntu-latest
    needs: my-build
    steps:
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
